# Generated by Django 4.1.9 on 2023-10-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.TextField()),
                ("org_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
            options={
                "unique_together": {("url", "org_id", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="FileVersionInformation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.BinaryField()),
                (
                    "file_version_id",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="file_versions.file"),
                ),
            ],
            options={
                "unique_together": {("file_version_id", "version_number")},
            },
        ),
        migrations.DeleteModel(
            name="FileVersion",
        ),
    ]
